name: Daily Weather & Outfit Recommendations

on:
  schedule:
    # Runs at 6 AM UTC every day
    - cron: '0 6 * * *'
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and run Docker container
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
        run: |
          docker build -t dress-weatherly .
          docker run --rm \
            -e SENDER_EMAIL \
            -e SENDER_APP_PASSWORD \
            dress-weatherly